# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6893252570268f8ac24cd45a99aa4bc4f3572b6809c4d5c553b8608b1bd29395a39d3d990527468ec5133a94c3944085faf64b2270b1b811b60b9225ecb454

test:
  secret_key_base: b5a840fee9ed8c33e58e85cd2ce551f810173fe35a8e2263b78e0df913d354cee57fcd56ccbd30e43e02c651a80eaef10605b70f0f79e8228c9c9b117f6cbcbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
